#+TITLE: Ekvivalenčne relacije in kvocientne množice
#+AUTHOR: Patrik Žnidaršič

* Ekvivalenčne relacije

Za relacijo =R ⊆ A ⨯ A= pravimo, da je /ekvivalenčna/, če je:
- refleksivna
- simetrična
- tranzitivna

Najbolj preprosta primera ekvivalenčnih relacij sta univerzalna relacija in diagonala.

Za ekvivalenčno relacijo =E= na množici =A= lahko definiramo /ekvivalenčne razrede/:
                           =[x]_E = {y ∈ A | x E y}=
                           
* Kvocientne množice

Naj bo =E= ekvivalenčna relacija na =A=. Tedaj razdeli množico =A= na ekvivalenčne razrede, ki so neprazni, med seboj disjunktni in pokrijejo celotno množico; (pravimo, da je to /particija/ ali /razdelitev/ množice =A=)
- nepraznost: sledi iz definicije.
- disjunktnost: če imata =[x]= in =[y]= skupni element =z=, velja =x E z ∧ z E y=, iz česar sledi =x E y= in =[x] = [y]=.
- pokritje celotne množice: naj bo =x ∈ A=. Velja =x ∈ [x]=.

Množico vseh ekvivalenčnih razredov =E= na =A= imenujemo /kvocientna množica/ in označimo =A/E=;
                     =A/E = {ξ ∈ P(A) | ∃ x ∈ A . ξ = [x]}=
Definiramo lahko /kvocientno preslikavo/ =q: A → A/E= s predpisom =x → [x]=. Zanjo velja, da je surjektivna; naj bo =B ∈ A/E=. Ker je =B= neprazen, obstaja =x ∈ B=. Tedaj velja =[x] = B=, in =q(x) = B=.

** Porojenost s preslikavo

Ekvivalenčna relacija je lahko porojena s preslikavo; če je =f: A → B= funkcija, potem je relacija =~_f= na =A=, podana s predpisom =a ~_f b ⇔ f(a) = f(b)=, ekvivalenčna; refleksivnost, simetričnost in tranzitivnost relacije sledijo iz istih lastnosti relacije ===.

Pravzaprav je vsaka ekvivalenčna relacija porojena s preslikavo; to je ravno kvocientna preslikava.

** Definicija preslikave na kvocientni domeni
   
Kadar želimo definirati preslikavo na kvocientni množici, moramo preveriti, da je dobro definirana; drugače povedano, če definiramo =f: A/E → B=, mora veljati =∀ x,y ∈ A. x E y ⇒ f(x) = f(y)=.

** Izbor predstavnikov

Naj bo =E= ekvivalenčna relacija na =A=. Množico =C ⊆ A=, ki vsak ekvivalenčni razred =E= seka v natanko eni točki, imenujemo /izbor predstavnikv/ za =E=. Izbor predstavnikov določa preslikavo =c: A/E → A=, ki vsakemu ekvivalenčnemu razredu priredi njegovega predstavnika. Ta preslikava je prerez kvocientne preslikave =q=.

Pravzaprav vsak prerez =s: A/E → A= kvocientne preslikave določa izbor predstavnikov s svojo sliko;
Naj bo =y ∈ s_*(A/E)=. Tedaj je =y ∈ [y]=. Naj bo =[x] ∈ A/E=. Vemo =[x] = q(s([x]))=, iz česar sledi =[x] = [s([x])]=; torej se sekata.

* Univeerzalna lastnost kvocientne množice

Naj bo =E= ekvivalenčna relacija na =A= in =g: A → B= preslikava, skladna z =E=. Tedaj obstaja natanko ena preslikava =f: A/E → B=, da je =f([x]) = g(x)= za vse =x ∈ A= (=f ∘ q = g=).

Dokažimo, da je največ ena taka preslikava; če sta =f_1= in =f_2= taki, potem velja =f_1 ∘ q = f_2 ∘ q=, ker pa je =q= epimorfizem, ga smemo krajšati na desni.

=f= bomo podali s funkcijsko relacijo =ϕ ⊆ A/E ⨯ B=;
                     =ϕ(ξ,y) :⇔ ∃ x ∈ ξ . g(x) = y=
                     
Preverimo, da je res funkcijska:
- enoličnost: sledi iz skladnosti =g= z =E=
- celovitost: sledi iz nepraznosti ekvivalenčnega razreda
  
Naj bo =x ∈ A=. Dokažimo =f([x]) = g(x)=; označimo =ξ = [x]=. Ker velja =x ∈ ξ= in =g(x) = g(x)=, je =f([x]) = g(x)=.

* Kanonična razdelitev preslikave

Naj bo =f: A → B= preslikava. Tedaj jo lahko razčlenimo na dve preslikavi =q: A → C= in =i: C → B=, da velja =i ∘ q = f= in: =q= je surjektivna, =i= pa injektivna. Taki razcepi so do izomorfizma natančno enaki.
